# Set some directory variables;
# Then start Prolog.

# Jena ARQ directory.
export ARQROOT=/home/dsb5/CHAIN/code/jena/apache-jena-2.12.0
export PATH="${ARQROOT}/bin:${PATH}"

#Locate the DAISY components
export DAISY_HOME=/home/dsb5/CHAIN/code/daisy-spsm

# Locate the OAEI conference dataset files to be used for this analysis
export OAEI_HOME=/home/dsb5/CHAIN/OAEI/analysis-2014

# Directory for temporary files generated by the system as it runs
export DAISY_RUNFILES="${DAISY_HOME}/OAEI/runfiles"
# Put the output file in the same place
export DAISY_OUTPUT="${DAISY_HOME}/OAEI/output"

# Delete all the temporary files (except the SPSM ones)
rm $DAISY_RUNFILES/*

# SICSTUS version
#sicstus --noinfo -l compareOAEI.pl 
# SWI-Prolog version
pl -s compareOAEI.pl 


