% There are 4 terms in this file:
% subclassOf/2
% geographicsubregion/2
% instanceOf/2
% overlapsspatially/2
% Each parameter is a set of individual words.

subclassOf([physical],[entity]).
subclassOf([object],[physical]).
subclassOf([self,connected,object],[object]).
subclassOf([organic,thing],[self,connected,object]).
subclassOf([substance],[self,connected,object]).
subclassOf([syntheticsubstance],[substance]).
subclassOf([natural,substance],[substance]).
subclassOf([pure,substance],[substance]).
subclassOf([elemental,substance],[pure,substance]).
subclassOf([metal],[elemental,substance]).
subclassOf([atom],[elemental,substance]).
subclassOf([subatomic,particle],[elemental,substance]).
subclassOf([atomic,nucleus],[subatomic,particle]).
subclassOf([electron],[subatomic,particle]).
subclassOf([proton],[subatomic,particle]).
subclassOf([neutron],[subatomic,particle]).
subclassOf([compound,substance],[pure,substance]).
subclassOf([mixture],[substance]).
subclassOf([corpuscular,object],[self,connected,object]).
subclassOf([region],[object]).
subclassOf([collection],[object]).
subclassOf([content,bearing,physical],[physical]).
subclassOf([content,bearing,process],[content,bearing,physical]).
subclassOf([content,bearing,process],[process]).
subclassOf([content,bearing,object],[corpuscular,object]).
subclassOf([content,bearing,object],[content,bearing,physical]).
subclassOf([symbolicstring],[content,bearing,object]).
subclassOf([character],[symbolicstring]).
subclassOf([icon],[content,bearing,physical]).
subclassOf([motion,picture],[text]).
subclassOf([linguistic,expression],[content,bearing,physical]).
subclassOf([language],[linguistic,expression]).
subclassOf([animal,language],[language]).
subclassOf([artificial,language],[language]).
subclassOf([computer,language],[artificial,language]).
subclassOf([human,language],[language]).
subclassOf([constructed,language],[human,language]).
subclassOf([constructed,language],[artificial,language]).
subclassOf([natural,language],[human,language]).
subclassOf([manual,human,language],[human,language]).
subclassOf([spoken,human,language],[human,language]).
subclassOf([word],[linguistic,expression]).
subclassOf([formula],[sentence]).
subclassOf([agent],[object]).
subclassOf([sentient,agent],[agent]).
subclassOf([cognitive,agent],[sentient,agent]).
subclassOf([legal,agent],[agent]).
subclassOf([process],[physical]).
subclassOf([dual,object,process],[process]).
subclassOf([single,agent,process],[process]).
subclassOf([abstract],[entity]).
subclassOf([quantity],[abstract]).
subclassOf([attribute],[abstract]).
subclassOf([internal,attribute],[attribute]).
subclassOf([physical,attribute],[internal,attribute]).
subclassOf([relational,attribute],[attribute]).
subclassOf([number],[quantity]).
subclassOf([real,number],[number]).
subclassOf([imaginary,number],[number]).
subclassOf([rational,number],[real,number]).
subclassOf([irrational,number],[real,number]).
subclassOf([nonnegative,real,number],[real,number]).
subclassOf([positive,real,number],[nonnegative,real,number]).
subclassOf([negative,real,number],[real,number]).
subclassOf([integer],[rational,number]).
subclassOf([even,integer],[integer]).
subclassOf([odd,integer],[integer]).
subclassOf([prime,number],[integer]).
subclassOf([nonnegative,integer],[integer]).
subclassOf([nonnegative,integer],[nonnegative,real,number]).
subclassOf([negative,integer],[integer]).
subclassOf([negative,integer],[negative,real,number]).
subclassOf([positive,integer],[nonnegative,integer]).
subclassOf([positive,integer],[positive,real,number]).
subclassOf([binary,number],[real,number]).
subclassOf([complex,number],[number]).
subclassOf([physical,quantity],[quantity]).
subclassOf([constant,quantity],[physical,quantity]).
subclassOf([time,measure],[constant,quantity]).
subclassOf([time,duration],[time,measure]).
subclassOf([time,position],[time,measure]).
subclassOf([time,interval],[time,position]).
subclassOf([time,point],[time,position]).
subclassOf([function,quantity],[physical,quantity]).
subclassOf([unary,constant,function,quantity],[function,quantity]).
subclassOf([time,dependent,quantity],[unary,constant,function,quantity]).
subclassOf([set,or,class],[abstract]).
subclassOf([class],[set,or,class]).
subclassOf([set],[set,or,class]).
subclassOf([relation],[abstract]).
subclassOf([single,valued,relation],[relation]).
subclassOf([single,valued,relation],[inheritable,relation]).
subclassOf([total,valued,relation],[relation]).
subclassOf([total,valued,relation],[inheritable,relation]).
subclassOf([partial,valued,relation],[relation]).
subclassOf([binary,relation],[relation]).
subclassOf([binary,relation],[inheritable,relation]).
subclassOf([reflexive,relation],[binary,relation]).
subclassOf([irreflexive,relation],[binary,relation]).
subclassOf([symmetric,relation],[binary,relation]).
subclassOf([asymmetric,relation],[irreflexive,relation]).
subclassOf([asymmetric,relation],[antisymmetric,relation]).
subclassOf([antisymmetric,relation],[binary,relation]).
subclassOf([trichotomizing,relation],[binary,relation]).
subclassOf([transitive,relation],[binary,relation]).
subclassOf([intransitive,relation],[binary,relation]).
subclassOf([partial,ordering,relation],[transitive,relation]).
subclassOf([partial,ordering,relation],[antisymmetric,relation]).
subclassOf([partial,ordering,relation],[reflexive,relation]).
subclassOf([total,ordering,relation],[partial,ordering,relation]).
subclassOf([total,ordering,relation],[trichotomizing,relation]).
subclassOf([equivalence,relation],[transitive,relation]).
subclassOf([equivalence,relation],[symmetric,relation]).
subclassOf([equivalence,relation],[reflexive,relation]).
subclassOf([case,role],[binary,predicate]).
subclassOf([case,role],[inheritable,relation]).
subclassOf([case,role],[asymmetric,relation]).
subclassOf([inheritable,relation],[relation]).
subclassOf([probability,relation],[relation]).
subclassOf([probability,relation],[inheritable,relation]).
subclassOf([spatial,relation],[relation]).
subclassOf([spatial,relation],[inheritable,relation]).
subclassOf([temporal,relation],[relation]).
subclassOf([temporal,relation],[inheritable,relation]).
subclassOf([intentional,relation],[inheritable,relation]).
subclassOf([intentional,relation],[relation]).
subclassOf([propositional,attitude],[intentional,relation]).
subclassOf([propositional,attitude],[asymmetric,relation]).
subclassOf([propositional,attitude],[inheritable,relation]).
subclassOf([object,attitude],[intentional,relation]).
subclassOf([object,attitude],[inheritable,relation]).
subclassOf([ternary,relation],[relation]).
subclassOf([ternary,relation],[inheritable,relation]).
subclassOf([quaternary,relation],[relation]).
subclassOf([quaternary,relation],[inheritable,relation]).
subclassOf([quintary,relation],[relation]).
subclassOf([quintary,relation],[inheritable,relation]).
subclassOf([list],[relation]).
subclassOf([unique,list],[list]).
subclassOf([predicate],[relation]).
subclassOf([predicate],[inheritable,relation]).
subclassOf([function],[single,valued,relation]).
subclassOf([function],[inheritable,relation]).
subclassOf([unary,function],[function]).
subclassOf([unary,function],[binary,relation]).
subclassOf([unary,function],[inheritable,relation]).
subclassOf([one,to,one,function],[unary,function]).
subclassOf([sequence,function],[one,to,one,function]).
subclassOf([binary,function],[function]).
subclassOf([binary,function],[ternary,relation]).
subclassOf([binary,function],[inheritable,relation]).
subclassOf([associative,function],[binary,function]).
subclassOf([commutative,function],[binary,function]).
subclassOf([ternary,function],[function]).
subclassOf([ternary,function],[quaternary,relation]).
subclassOf([ternary,function],[inheritable,relation]).
subclassOf([quaternary,function],[function]).
subclassOf([quaternary,function],[quintary,relation]).
subclassOf([quaternary,function],[inheritable,relation]).
subclassOf([continuous,function],[function]).
subclassOf([binary,predicate],[predicate]).
subclassOf([binary,predicate],[binary,relation]).
subclassOf([binary,predicate],[inheritable,relation]).
subclassOf([ternary,predicate],[predicate]).
subclassOf([ternary,predicate],[ternary,relation]).
subclassOf([ternary,predicate],[inheritable,relation]).
subclassOf([quaternary,predicate],[predicate]).
subclassOf([quaternary,predicate],[quaternary,relation]).
subclassOf([quaternary,predicate],[inheritable,relation]).
subclassOf([quintary,predicate],[predicate]).
subclassOf([quintary,predicate],[quintary,relation]).
subclassOf([quintary,predicate],[inheritable,relation]).
subclassOf([variable,arity,relation],[relation]).
subclassOf([relation,extended,to,quantities],[relation]).
subclassOf([relation,extended,to,quantities],[inheritable,relation]).
subclassOf([logical,operator],[predicate]).
subclassOf([proposition],[abstract]).
subclassOf([null,set],[set,or,class]).
subclassOf([non,null,set],[set,or,class]).
subclassOf([finite,set],[set]).
subclassOf([pairwise,disjoint,class],[set,or,class]).
subclassOf([mutually,disjoint,class],[set,or,class]).
subclassOf([graph],[abstract]).
subclassOf([directed,graph],[graph]).
subclassOf([tree],[directed,graph]).
subclassOf([graph,path],[directed,graph]).
subclassOf([graph,circuit],[graph,path]).
subclassOf([multi,graph],[graph]).
subclassOf([pseudo,graph],[graph]).
subclassOf([graph,element],[abstract]).
subclassOf([graph,node],[graph,element]).
subclassOf([graph,arc],[graph,element]).
subclassOf([graph,loop],[graph,arc]).
subclassOf([physical,system],[physical]).
subclassOf([unit,of,measure],[physical,quantity]).
subclassOf([composite,unit,of,measure],[unit,of,measure]).
subclassOf([non,composite,unit,of,measure],[unit,of,measure]).
subclassOf([systeme,international,unit],[unit,of,measure]).
subclassOf([length,measure],[constant,quantity]).
subclassOf([unit,of,length],[non,composite,unit,of,measure]).
subclassOf([mass,measure],[constant,quantity]).
subclassOf([unit,of,mass],[non,composite,unit,of,measure]).
subclassOf([area,measure],[function,quantity]).
subclassOf([unit,of,area],[composite,unit,of,measure]).
subclassOf([volume,measure],[function,quantity]).
subclassOf([unit,of,volume],[composite,unit,of,measure]).
subclassOf([temperature,measure],[constant,quantity]).
subclassOf([unit,of,temperature],[non,composite,unit,of,measure]).
subclassOf([currency,measure],[constant,quantity]).
subclassOf([unit,of,currency],[non,composite,unit,of,measure]).
subclassOf([angle,measure],[constant,quantity]).
subclassOf([unit,of,angular,measure],[non,composite,unit,of,measure]).
subclassOf([plane,angle,measure],[angle,measure]).
subclassOf([solid,angle,measure],[angle,measure]).
subclassOf([unit,of,information],[non,composite,unit,of,measure]).
subclassOf([unit,of,duration],[non,composite,unit,of,measure]).
subclassOf([unit,of,measure,multiplier],[unary,function]).
subclassOf([unit,of,measure,multiplier],[total,valued,relation]).
subclassOf([frequency,measure],[time,dependent,quantity]).
subclassOf([unit,of,frequency],[composite,unit,of,measure]).
subclassOf([information,measure],[constant,quantity]).
subclassOf([oval],[closed,two,dimensional,figure]).
subclassOf([circle],[oval]).
subclassOf([unit,of,atmospheric,pressure],[composite,unit,of,measure]).
subclassOf([year],[time,interval]).
subclassOf([leap,year],[year]).
subclassOf([month],[time,interval]).
subclassOf([january],[month]).
subclassOf([february],[month]).
subclassOf([march],[month]).
subclassOf([april],[month]).
subclassOf([may],[month]).
subclassOf([june],[month]).
subclassOf([july],[month]).
subclassOf([august],[month]).
subclassOf([september],[month]).
subclassOf([october],[month]).
subclassOf([november],[month]).
subclassOf([december],[month]).
subclassOf([day],[time,interval]).
subclassOf([monday],[day]).
subclassOf([tuesday],[day]).
subclassOf([wednesday],[day]).
subclassOf([thursday],[day]).
subclassOf([friday],[day]).
subclassOf([saturday],[day]).
subclassOf([sunday],[day]).
subclassOf([week],[time,interval]).
subclassOf([hour],[time,interval]).
subclassOf([minute],[time,interval]).
subclassOf([second],[time,interval]).
subclassOf([hole],[region]).
subclassOf([biological,process],[internal,change]).
subclassOf([physiologic,process],[biological,process]).
subclassOf([autonomic,process],[physiologic,process]).
subclassOf([organ,or,tissue,process],[autonomic,process]).
subclassOf([organism,process],[physiologic,process]).
subclassOf([birth],[organism,process]).
subclassOf([death],[organism,process]).
subclassOf([breathing],[organism,process]).
subclassOf([breathing],[autonomic,process]).
subclassOf([ingesting],[organism,process]).
subclassOf([eating],[ingesting]).
subclassOf([drinking],[ingesting]).
subclassOf([digesting],[organism,process]).
subclassOf([digesting],[autonomic,process]).
subclassOf([growth],[autonomic,process]).
subclassOf([replication],[organism,process]).
subclassOf([sexual,reproduction],[replication]).
subclassOf([asexual,reproduction],[replication]).
subclassOf([psychological,process],[biological,process]).
subclassOf([pathologic,process],[biological,process]).
subclassOf([injuring],[pathologic,process]).
subclassOf([injuring],[damaging]).
subclassOf([poisoning],[injuring]).
subclassOf([natural,process],[process]).
subclassOf([intentional,process],[process]).
subclassOf([intentional,psychological,process],[intentional,process]).
subclassOf([intentional,psychological,process],[psychological,process]).
subclassOf([recreation,or,exercise],[intentional,process]).
subclassOf([organizational,process],[intentional,process]).
subclassOf([election],[organizational,process]).
subclassOf([religious,process],[organizational,process]).
subclassOf([joining,an,organization],[organizational,process]).
subclassOf([leaving,an,organization],[organizational,process]).
subclassOf([graduation],[leaving,an,organization]).
subclassOf([matriculation],[joining,an,organization]).
subclassOf([hiring],[joining,an,organization]).
subclassOf([terminating,employment],[leaving,an,organization]).
subclassOf([political,process],[organizational,process]).
subclassOf([judicial,process],[political,process]).
subclassOf([legal,decision],[judicial,process]).
subclassOf([legal,decision],[declaring]).
subclassOf([military,process],[political,process]).
subclassOf([military,process],[organizational,process]).
subclassOf([regulatory,process],[guiding]).
subclassOf([managing],[organizational,process]).
subclassOf([managing],[guiding]).
subclassOf([planning],[intentional,psychological,process]).
subclassOf([designing],[intentional,psychological,process]).
subclassOf([interpreting],[intentional,psychological,process]).
subclassOf([quantity,change],[internal,change]).
subclassOf([increasing],[quantity,change]).
subclassOf([heating],[increasing]).
subclassOf([decreasing],[quantity,change]).
subclassOf([cooling],[decreasing]).
subclassOf([motion],[process]).
subclassOf([motion,upward],[motion]).
subclassOf([motion,downward],[motion]).
subclassOf([body,motion],[motion]).
subclassOf([vocal,cords],[organ]).
subclassOf([vocalizing],[radiating,sound]).
subclassOf([speaking],[linguistic,communication]).
subclassOf([speaking],[vocalizing]).
subclassOf([ambulating],[body,motion]).
subclassOf([ambulating],[translocation]).
subclassOf([walking],[ambulating]).
subclassOf([running],[ambulating]).
subclassOf([swimming],[body,motion]).
subclassOf([dancing],[body,motion]).
subclassOf([geological,process],[motion]).
subclassOf([geological,process],[internal,change]).
subclassOf([weather,process],[motion]).
subclassOf([precipitation],[weather,process]).
subclassOf([precipitation],[water,motion]).
subclassOf([precipitation],[falling]).
subclassOf([liquid,motion],[motion]).
subclassOf([water,motion],[liquid,motion]).
subclassOf([gas,motion],[motion]).
subclassOf([wind],[gas,motion]).
subclassOf([direction,change],[motion]).
subclassOf([transfer],[translocation]).
subclassOf([carrying],[transfer]).
subclassOf([removing],[transfer]).
subclassOf([uncovering],[removing]).
subclassOf([putting],[transfer]).
subclassOf([covering],[putting]).
subclassOf([inserting],[putting]).
subclassOf([injecting],[inserting]).
subclassOf([substituting],[transfer]).
subclassOf([substituting],[dual,object,process]).
subclassOf([impelling],[transfer]).
subclassOf([shooting],[impelling]).
subclassOf([touching],[transfer]).
subclassOf([grabbing],[touching]).
subclassOf([grabbing],[attaching]).
subclassOf([releasing],[transfer]).
subclassOf([impacting],[touching]).
subclassOf([translocation],[motion]).
subclassOf([falling],[translocation]).
subclassOf([falling],[motion,downward]).
subclassOf([transportation],[translocation]).
subclassOf([guiding],[intentional,process]).
subclassOf([driving],[guiding]).
subclassOf([educational,process],[guiding]).
subclassOf([change,of,possession],[social,interaction]).
subclassOf([giving],[change,of,possession]).
subclassOf([funding],[giving]).
subclassOf([unilateral,giving],[giving]).
subclassOf([lending],[giving]).
subclassOf([giving,back],[giving]).
subclassOf([getting],[change,of,possession]).
subclassOf([unilateral,getting],[getting]).
subclassOf([borrowing],[getting]).
subclassOf([transaction],[change,of,possession]).
subclassOf([transaction],[dual,object,process]).
subclassOf([financial,transaction],[transaction]).
subclassOf([service,process],[social,interaction]).
subclassOf([commercial,service],[financial,transaction]).
subclassOf([commercial,service],[service,process]).
subclassOf([betting],[financial,transaction]).
subclassOf([buying],[financial,transaction]).
subclassOf([selling],[financial,transaction]).
subclassOf([learning],[intentional,psychological,process]).
subclassOf([discovering],[intentional,psychological,process]).
subclassOf([classifying],[intentional,psychological,process]).
subclassOf([reasoning],[intentional,psychological,process]).
subclassOf([selecting],[intentional,psychological,process]).
subclassOf([deciding],[selecting]).
subclassOf([voting],[deciding]).
subclassOf([judging],[selecting]).
subclassOf([comparing],[intentional,psychological,process]).
subclassOf([comparing],[dual,object,process]).
subclassOf([calculating],[intentional,psychological,process]).
subclassOf([measuring],[calculating]).
subclassOf([counting],[calculating]).
subclassOf([predicting],[intentional,psychological,process]).
subclassOf([remembering],[psychological,process]).
subclassOf([keeping],[intentional,process]).
subclassOf([confining],[keeping]).
subclassOf([maintaining],[intentional,process]).
subclassOf([repairing],[intentional,process]).
subclassOf([therapeutic,process],[repairing]).
subclassOf([surgery],[therapeutic,process]).
subclassOf([damaging],[internal,change]).
subclassOf([destruction],[damaging]).
subclassOf([killing],[destruction]).
subclassOf([poking],[intentional,process]).
subclassOf([cutting],[poking]).
subclassOf([attaching],[dual,object,process]).
subclassOf([detaching],[dual,object,process]).
subclassOf([ungrasping],[detaching]).
subclassOf([combining],[dual,object,process]).
subclassOf([separating],[dual,object,process]).
subclassOf([chemical,process],[internal,change]).
subclassOf([chemical,synthesis],[chemical,process]).
subclassOf([chemical,synthesis],[combining]).
subclassOf([chemical,decomposition],[chemical,process]).
subclassOf([chemical,decomposition],[separating]).
subclassOf([combustion],[chemical,decomposition]).
subclassOf([internal,change],[process]).
subclassOf([surface,change],[internal,change]).
subclassOf([coloring],[surface,change]).
subclassOf([shape,change],[internal,change]).
subclassOf([content,development],[intentional,process]).
subclassOf([reading],[content,development]).
subclassOf([writing],[content,development]).
subclassOf([encoding],[writing]).
subclassOf([decoding],[writing]).
subclassOf([translating],[content,development]).
subclassOf([translating],[dual,object,process]).
subclassOf([wetting],[putting]).
subclassOf([drying],[removing]).
subclassOf([creation],[internal,change]).
subclassOf([making],[creation]).
subclassOf([making],[intentional,process]).
subclassOf([constructing],[making]).
subclassOf([manufacture],[making]).
subclassOf([publication],[manufacture]).
subclassOf([publication],[content,development]).
subclassOf([cooking],[making]).
subclassOf([pursuing],[intentional,process]).
subclassOf([hunting],[pursuing]).
subclassOf([investigating],[intentional,psychological,process]).
subclassOf([experimenting],[investigating]).
subclassOf([diagnostic,process],[investigating]).
subclassOf([social,interaction],[intentional,process]).
subclassOf([pretending],[social,interaction]).
subclassOf([communication],[social,interaction]).
subclassOf([communication],[content,bearing,process]).
subclassOf([disseminating],[communication]).
subclassOf([demonstrating],[disseminating]).
subclassOf([gesture],[communication]).
subclassOf([gesture],[body,motion]).
subclassOf([advertising],[disseminating]).
subclassOf([expressing],[communication]).
subclassOf([linguistic,communication],[communication]).
subclassOf([stating],[linguistic,communication]).
subclassOf([disagreeing],[stating]).
subclassOf([supposing],[linguistic,communication]).
subclassOf([directing],[linguistic,communication]).
subclassOf([ordering],[directing]).
subclassOf([requesting],[directing]).
subclassOf([questioning],[directing]).
subclassOf([committing],[linguistic,communication]).
subclassOf([offering],[committing]).
subclassOf([declaring],[linguistic,communication]).
subclassOf([naming],[declaring]).
subclassOf([cooperation],[social,interaction]).
subclassOf([meeting],[social,interaction]).
subclassOf([contest],[social,interaction]).
subclassOf([violent,contest],[contest]).
subclassOf([war],[violent,contest]).
subclassOf([battle],[violent,contest]).
subclassOf([game],[contest]).
subclassOf([game],[recreation,or,exercise]).
subclassOf([sport],[game]).
subclassOf([legal,action],[contest]).
subclassOf([maneuver],[intentional,process]).
subclassOf([attack],[maneuver]).
subclassOf([defensive,maneuver],[maneuver]).
subclassOf([perception],[psychological,process]).
subclassOf([seeing],[perception]).
subclassOf([looking],[seeing]).
subclassOf([looking],[intentional,process]).
subclassOf([smelling],[perception]).
subclassOf([tasting],[perception]).
subclassOf([hearing],[perception]).
subclassOf([sound,attribute],[perceptual,attribute]).
subclassOf([sound,attribute],[relational,attribute]).
subclassOf([listening],[hearing]).
subclassOf([listening],[intentional,process]).
subclassOf([tactile,perception],[perception]).
subclassOf([radiating],[motion]).
subclassOf([radiating,light],[radiating,electromagnetic]).
subclassOf([radiating,infrared],[radiating,electromagnetic]).
subclassOf([radiating,x,ray],[radiating,electromagnetic]).
subclassOf([radiating,sound],[radiating]).
subclassOf([making,music],[radiating,sound]).
subclassOf([making,instrumental,music],[making,music]).
subclassOf([making,vocal,music],[making,music]).
subclassOf([making,vocal,music],[vocalizing]).
subclassOf([singing],[making,vocal,music]).
subclassOf([radiating,electromagnetic],[radiating]).
subclassOf([radiating,nuclear],[radiating]).
subclassOf([state,change],[internal,change]).
subclassOf([melting],[state,change]).
subclassOf([boiling],[state,change]).
subclassOf([evaporating],[state,change]).
subclassOf([condensing],[state,change]).
subclassOf([freezing],[state,change]).
subclassOf([astronomical,body],[object]).
subclassOf([geographic,area],[region]).
subclassOf([localizable,place],[geographic,area]).
subclassOf([geopolitical,area],[geographic,area]).
subclassOf([geopolitical,area],[agent]).
subclassOf([water,area],[geographic,area]).
subclassOf([salt,water,area],[water,area]).
subclassOf([fresh,water,area],[water,area]).
subclassOf([land,area],[geographic,area]).
subclassOf([shore,area],[land,area]).
subclassOf([continent],[land,area]).
subclassOf([island],[land,area]).
subclassOf([nation],[geopolitical,area]).
subclassOf([nation],[land,area]).
subclassOf([state,or,province],[geopolitical,area]).
subclassOf([state,or,province],[land,area]).
subclassOf([city],[geopolitical,area]).
subclassOf([city],[land,area]).
subclassOf([county],[geopolitical,area]).
subclassOf([county],[land,area]).
subclassOf([transitway],[region]).
subclassOf([transitway],[self,connected,object]).
subclassOf([land,transitway],[transitway]).
subclassOf([land,transitway],[land,area]).
subclassOf([roadway],[land,transitway]).
subclassOf([water],[compound,substance]).
subclassOf([mineral],[substance]).
subclassOf([organic,object],[corpuscular,object]).
subclassOf([organic,object],[organic,thing]).
subclassOf([organism],[organic,object]).
subclassOf([organism],[agent]).
subclassOf([plant],[organism]).
subclassOf([flowering,plant],[plant]).
subclassOf([non,flowering,plant],[plant]).
subclassOf([alga],[non,flowering,plant]).
subclassOf([fungus],[organism]).
subclassOf([moss],[non,flowering,plant]).
subclassOf([fern],[non,flowering,plant]).
subclassOf([animal],[organism]).
subclassOf([microorganism],[organism]).
subclassOf([bacterium],[microorganism]).
subclassOf([virus],[microorganism]).
subclassOf([vertebrate],[animal]).
subclassOf([invertebrate],[animal]).
subclassOf([worm],[invertebrate]).
subclassOf([mollusk],[invertebrate]).
subclassOf([arthropod],[invertebrate]).
subclassOf([arachnid],[arthropod]).
subclassOf([myriapod],[arthropod]).
subclassOf([insect],[arthropod]).
subclassOf([crustacean],[arthropod]).
subclassOf([cold,blooded,vertebrate],[vertebrate]).
subclassOf([warm,blooded,vertebrate],[vertebrate]).
subclassOf([amphibian],[cold,blooded,vertebrate]).
subclassOf([bird],[warm,blooded,vertebrate]).
subclassOf([fish],[cold,blooded,vertebrate]).
subclassOf([mammal],[warm,blooded,vertebrate]).
subclassOf([aquatic,mammal],[mammal]).
subclassOf([hoofed,mammal],[mammal]).
subclassOf([marsupial],[mammal]).
subclassOf([carnivore],[mammal]).
subclassOf([canine],[carnivore]).
subclassOf([feline],[carnivore]).
subclassOf([rodent],[mammal]).
subclassOf([primate],[mammal]).
subclassOf([ape],[primate]).
subclassOf([monkey],[primate]).
subclassOf([hominid],[primate]).
subclassOf([human],[hominid]).
subclassOf([human],[cognitive,agent]).
subclassOf([man],[human]).
subclassOf([woman],[human]).
subclassOf([reptile],[cold,blooded,vertebrate]).
subclassOf([biologically,active,substance],[substance]).
subclassOf([nutrient],[biologically,active,substance]).
subclassOf([protein],[nutrient]).
subclassOf([enzyme],[protein]).
subclassOf([carbohydrate],[nutrient]).
subclassOf([vitamin],[nutrient]).
subclassOf([liquid,mixture],[mixture]).
subclassOf([solution],[liquid,mixture]).
subclassOf([suspension],[liquid,mixture]).
subclassOf([gas,mixture],[mixture]).
subclassOf([cloud],[gas,mixture]).
subclassOf([smoke],[cloud]).
subclassOf([water,cloud],[cloud]).
subclassOf([air],[gas,mixture]).
subclassOf([body,substance],[substance]).
subclassOf([animal,substance],[body,substance]).
subclassOf([plant,substance],[body,substance]).
subclassOf([hormone],[body,substance]).
subclassOf([hormone],[biologically,active,substance]).
subclassOf([blood],[body,substance]).
subclassOf([meat],[self,connected,object]).
subclassOf([anatomical,structure],[organic,object]).
subclassOf([abnormal,anatomical,structure],[anatomical,structure]).
subclassOf([body,part],[anatomical,structure]).
subclassOf([animal,anatomical,structure],[anatomical,structure]).
subclassOf([plant,anatomical,structure],[anatomical,structure]).
subclassOf([reproductive,body],[body,part]).
subclassOf([egg],[reproductive,body]).
subclassOf([egg],[animal,anatomical,structure]).
subclassOf([seed],[reproductive,body]).
subclassOf([seed],[plant,anatomical,structure]).
subclassOf([pollen],[reproductive,body]).
subclassOf([pollen],[plant,anatomical,structure]).
subclassOf([fruit,or,vegetable],[plant,anatomical,structure]).
subclassOf([fruit,or,vegetable],[reproductive,body]).
subclassOf([spore],[reproductive,body]).
subclassOf([spore],[plant,anatomical,structure]).
subclassOf([body,covering],[body,part]).
subclassOf([body,junction],[body,part]).
subclassOf([body,cavity],[body,part]).
subclassOf([body,vessel],[body,cavity]).
subclassOf([cell],[body,part]).
subclassOf([organ],[body,part]).
subclassOf([gland],[organ]).
subclassOf([tissue],[body,substance]).
subclassOf([bone],[tissue]).
subclassOf([bone],[animal,substance]).
subclassOf([muscle],[tissue]).
subclassOf([muscle],[animal,substance]).
subclassOf([fat,tissue],[tissue]).
subclassOf([noun],[word]).
subclassOf([verb],[word]).
subclassOf([adjective],[word]).
subclassOf([adverb],[word]).
subclassOf([particle,word],[word]).
subclassOf([morpheme],[linguistic,expression]).
subclassOf([phrase],[linguistic,expression]).
subclassOf([verb,phrase],[phrase]).
subclassOf([noun,phrase],[phrase]).
subclassOf([prepositional,phrase],[phrase]).
subclassOf([text],[linguistic,expression]).
subclassOf([text],[content,bearing,object]).
subclassOf([text],[artifact]).
subclassOf([factual,text],[text]).
subclassOf([fictional,text],[text]).
subclassOf([sentence],[linguistic,expression]).
subclassOf([summary],[text]).
subclassOf([certificate],[text]).
subclassOf([financial,instrument],[certificate]).
subclassOf([currency],[financial,instrument]).
subclassOf([patent],[certificate]).
subclassOf([molecule],[compound,substance]).
subclassOf([artifact],[object]).
subclassOf([product],[artifact]).
subclassOf([stationary,artifact],[artifact]).
subclassOf([building],[stationary,artifact]).
subclassOf([room],[stationary,artifact]).
subclassOf([house],[residential,building]).
subclassOf([house],[single,family,residence]).
subclassOf([residence],[stationary,artifact]).
subclassOf([permanent,residence],[residence]).
subclassOf([temporary,residence],[residence]).
subclassOf([residential,building],[building]).
subclassOf([residential,building],[residence]).
subclassOf([single,family,residence],[permanent,residence]).
subclassOf([art,work],[artifact]).
subclassOf([representational,art,work],[art,work]).
subclassOf([representational,art,work],[icon]).
subclassOf([fabric],[artifact]).
subclassOf([wearable,item],[artifact]).
subclassOf([clothing],[wearable,item]).
subclassOf([device],[artifact]).
subclassOf([musical,instrument],[device]).
subclassOf([transportation,device],[device]).
subclassOf([vehicle],[transportation,device]).
subclassOf([measuring,device],[device]).
subclassOf([attaching,device],[device]).
subclassOf([weapon],[device]).
subclassOf([machine],[device]).
subclassOf([engineering,component],[device]).
subclassOf([engineering,connection],[engineering,component]).
subclassOf([commercial,agent],[agent]).
subclassOf([business],[commercial,agent]).
subclassOf([business],[organization]).
subclassOf([corporation],[business]).
subclassOf([corporation],[legal,agent]).
subclassOf([manufacturer],[corporation]).
subclassOf([mercantile,organization],[corporation]).
subclassOf([group],[collection]).
subclassOf([group],[agent]).
subclassOf([group,of,people],[group]).
subclassOf([age,group],[group,of,people]).
subclassOf([family,group],[group,of,people]).
subclassOf([social,unit],[group,of,people]).
subclassOf([ethnic,group],[group,of,people]).
subclassOf([belief,group],[group,of,people]).
subclassOf([organization],[group]).
subclassOf([organization],[agent]).
subclassOf([political,organization],[organization]).
subclassOf([military,force],[political,organization]).
subclassOf([military,organization],[military,force]).
subclassOf([military,organization],[government,organization]).
subclassOf([paramilitary,organization],[military,force]).
subclassOf([government,organization],[organization]).
subclassOf([government],[government,organization]).
subclassOf([government],[legal,agent]).
subclassOf([police,organization],[government,organization]).
subclassOf([judicial,organization],[organization]).
subclassOf([educational,organization],[organization]).
subclassOf([religious,organization],[organization]).
subclassOf([religious,organization],[belief,group]).
subclassOf([field,of,study],[proposition]).
subclassOf([procedure],[proposition]).
subclassOf([computer,program],[procedure]).
subclassOf([computer,programming],[content,development]).
subclassOf([plan],[procedure]).
subclassOf([argument],[proposition]).
subclassOf([deductive,argument],[argument]).
subclassOf([valid,deductive,argument],[deductive,argument]).
subclassOf([invalid,deductive,argument],[deductive,argument]).
subclassOf([explanation],[deductive,argument]).
subclassOf([inductive,argument],[argument]).
subclassOf([truth,value],[relational,attribute]).
subclassOf([positional,attribute],[relational,attribute]).
subclassOf([directional,attribute],[positional,attribute]).
subclassOf([symmetric,positional,attribute],[positional,attribute]).
subclassOf([anti,symmetric,positional,attribute],[positional,attribute]).
subclassOf([time,zone],[relational,attribute]).
subclassOf([social,role],[relational,attribute]).
subclassOf([position],[social,role]).
subclassOf([normative,attribute],[relational,attribute]).
subclassOf([subjective,assessment,attribute],[normative,attribute]).
subclassOf([objective,norm],[normative,attribute]).
subclassOf([contest,attribute],[objective,norm]).
subclassOf([alethic,attribute],[objective,norm]).
subclassOf([deontic,attribute],[objective,norm]).
subclassOf([probability,attribute],[objective,norm]).
subclassOf([physical,state],[internal,attribute]).
subclassOf([perceptual,attribute],[attribute]).
subclassOf([taste,attribute],[perceptual,attribute]).
subclassOf([olfactory,attribute],[perceptual,attribute]).
subclassOf([visual,attribute],[perceptual,attribute]).
subclassOf([color,attribute],[visual,attribute]).
subclassOf([primary,color],[color,attribute]).
subclassOf([structure,attribute],[internal,attribute]).
subclassOf([shape,attribute],[structure,attribute]).
subclassOf([texture,attribute],[perceptual,attribute]).
subclassOf([geometric,figure],[shape,attribute]).
subclassOf([geometric,point],[geometric,figure]).
subclassOf([one,dimensional,figure],[geometric,figure]).
subclassOf([two,dimensional,figure],[geometric,figure]).
subclassOf([open,two,dimensional,figure],[two,dimensional,figure]).
subclassOf([two,dimensional,angle],[open,two,dimensional,figure]).
subclassOf([closed,two,dimensional,figure],[two,dimensional,figure]).
subclassOf([three,dimensional,figure],[geometric,figure]).
subclassOf([saturation,attribute],[internal,attribute]).
subclassOf([biological,attribute],[internal,attribute]).
subclassOf([body,position],[biological,attribute]).
subclassOf([animacy,attribute],[biological,attribute]).
subclassOf([sex,attribute],[biological,attribute]).
subclassOf([developmental,attribute],[biological,attribute]).
subclassOf([disease,or,syndrome],[biological,attribute]).
subclassOf([psychological,attribute],[biological,attribute]).
subclassOf([state,of,mind],[psychological,attribute]).
subclassOf([emotional,state],[state,of,mind]).
subclassOf([consciousness,attribute],[state,of,mind]).
subclassOf([trait,attribute],[psychological,attribute]).
subclassOf([psychological,dysfunction],[psychological,attribute]).
subclassOf([psychological,dysfunction],[disease,or,syndrome]).
subclassOf([latitude],[region]).
subclassOf([longitude],[region]).
subclassOf([surface,ground,area],[geographic,area]).
subclassOf([water,only,area],[geographic,area]).
subclassOf([binary,relation,extended,to,quantities],[relation,extended,to,quantities]).
subclassOf([binary,relation,extended,to,quantities],[binary,predicate]).
subclassOf([international,border],[geographic,area]).
subclassOf([checkpoint],[geographic,area]).
subclassOf([perimeter,area],[region]).
subclassOf([uniform,perimeter,area],[perimeter,area]).
subclassOf([landlocked,area],[land,area]).
subclassOf([maritime,claim,area],[geographic,area]).
subclassOf([maritime,contiguous,zone],[maritime,claim,area]).
subclassOf([maritime,contiguous,zone],[salt,water,area]).
subclassOf([maritime,shelf,area],[maritime,claim,area]).
subclassOf([maritime,shelf,area],[submerged,land,area]).
subclassOf([maritime,exclusive,economic,zone],[maritime,claim,area]).
subclassOf([maritime,exclusive,economic,zone],[salt,water,area]).
subclassOf([exclusive,fishing,zone],[maritime,claim,area]).
subclassOf([exclusive,fishing,zone],[salt,water,area]).
subclassOf([extended,fishing,zone],[maritime,claim,area]).
subclassOf([extended,fishing,zone],[salt,water,area]).
subclassOf([territorial,sea],[maritime,claim,area]).
subclassOf([territorial,sea],[salt,water,area]).
subclassOf([climate,zone],[geographic,area]).
subclassOf([tropical,climate,zone],[climate,zone]).
subclassOf([wet,tropical,climate,zone],[tropical,climate,zone]).
subclassOf([monsoon,climate,zone],[tropical,climate,zone]).
subclassOf([arid,climate,zone],[climate,zone]).
subclassOf([steppe,climate,zone],[arid,climate,zone]).
subclassOf([desert,climate,zone],[arid,climate,zone]).
subclassOf([subtropical,desert,climate,zone],[desert,climate,zone]).
subclassOf([middle,latitude,desert,climate,zone],[desert,climate,zone]).
subclassOf([semiarid,climate,zone],[climate,zone]).
subclassOf([temperate,climate,zone],[climate,zone]).
subclassOf([mediterranean,climate,zone],[temperate,climate,zone]).
subclassOf([continental,climate,zone],[temperate,climate,zone]).
subclassOf([midlatitude,continental,climate,zone],[climate,zone]).
subclassOf([temperate,winter,dry,climate,zone],[temperate,climate,zone]).
subclassOf([temperate,summer,dry,climate,zone],[temperate,climate,zone]).
subclassOf([cold,climate,zone],[climate,zone]).
subclassOf([cold,damp,climate,zone],[cold,climate,zone]).
subclassOf([dry,winter,cold,climate,zone],[cold,climate,zone]).
subclassOf([polar,climate,zone],[climate,zone]).
subclassOf([tundra,climate,zone],[polar,climate,zone]).
subclassOf([polar,type,f,climate,zone],[polar,climate,zone]).
subclassOf([terrain,attribute],[internal,attribute]).
subclassOf([barite],[compound,substance]).
subclassOf([barite],[mineral]).
subclassOf([brown,coal],[coal]).
subclassOf([chromite],[compound,substance]).
subclassOf([chromite],[mineral]).
subclassOf([coal],[mineral]).
subclassOf([coal],[fossil,fuel]).
subclassOf([coal],[rock]).
subclassOf([hydropower,water,area],[water,area]).
subclassOf([natural,gas],[compound,substance]).
subclassOf([phosphate],[compound,substance]).
subclassOf([potash],[compound,substance]).
subclassOf([talc],[mineral]).
subclassOf([arable,land],[land,area]).
subclassOf([permanent,crop,land],[land,area]).
subclassOf([irrigated,land],[land,area]).
subclassOf([avalanche,process],[impelling]).
subclassOf([landslide,process],[impelling]).
subclassOf([drought],[weather,process]).
subclassOf([earthquake],[geological,process]).
subclassOf([earth,tremor],[geological,process]).
subclassOf([earth,tremor],[tremor]).
subclassOf([aftershock],[earth,tremor]).
subclassOf([geological,fault],[geographic,area]).
subclassOf([dip,slip,fault],[geological,fault]).
subclassOf([normal,fault],[dip,slip,fault]).
subclassOf([thrust,fault],[dip,slip,fault]).
subclassOf([strike,slip,fault],[geological,fault]).
subclassOf([forest,fire],[combustion]).
subclassOf([grass,fire],[combustion]).
subclassOf([hurricane],[tropical,cyclone]).
subclassOf([tornado],[weather,process]).
subclassOf([tsunami],[weather,process]).
subclassOf([volcanic,eruption],[geological,process]).
subclassOf([acidification],[combining]).
subclassOf([air,pollution],[pollution]).
subclassOf([acid,rainfall],[weather,process]).
subclassOf([carbon,dioxide,emission],[separating]).
subclassOf([afforestation],[planting]).
subclassOf([planting],[putting]).
subclassOf([reforestation],[planting]).
subclassOf([asbestos],[mineral]).
subclassOf([biodiversity,attribute],[internal,attribute]).
subclassOf([carbon,cycle],[geological,process]).
subclassOf([water,catchment],[artifact]).
subclassOf([d,d,t],[compound,substance]).
subclassOf([defoliant],[pure,substance]).
subclassOf([deforestation],[removing]).
subclassOf([desertification],[weather,process]).
subclassOf([dredging],[removing]).
subclassOf([ecosystem],[geographic,area]).
subclassOf([effluent],[substance]).
subclassOf([endangered,species],[organism]).
subclassOf([erosion],[removing]).
subclassOf([erosion],[geological,process]).
subclassOf([fishing],[hunting]).
subclassOf([forest,damage],[damaging]).
subclassOf([forest,fire],[forest,damage]).
subclassOf([deforestation],[forest,damage]).
subclassOf([driftnet,fishing],[fishing]).
subclassOf([freshwater,overutilization],[social,interaction]).
subclassOf([freshwater],[water]).
subclassOf([greenhouse,gas],[pure,substance]).
subclassOf([groundwater],[water]).
subclassOf([industrial,pollution],[pollution]).
subclassOf([metallurgical,plant],[organization]).
subclassOf([noxioussubstance],[substance]).
subclassOf([overgrazing],[eating]).
subclassOf([pesticide,pollution],[pollution]).
subclassOf([poaching],[killing]).
subclassOf([pollution],[social,interaction]).
subclassOf([potable,water],[freshwater]).
subclassOf([salination],[combining]).
subclassOf([sanitation],[removing]).
subclassOf([sewage,disposal],[sanitation]).
subclassOf([solid,waste,disposal],[sanitation]).
subclassOf([siltation],[putting]).
subclassOf([slash,and,burn,agriculture],[agriculture]).
subclassOf([soil,degradation],[social,interaction]).
subclassOf([soil,erosion],[erosion]).
subclassOf([soil,salination],[salination]).
subclassOf([vehicular,pollution],[pollution]).
subclassOf([water,overutilization],[social,interaction]).
subclassOf([water,pollution],[pollution]).
subclassOf([international,agreement],[agreement]).
subclassOf([treaty,document],[text]).
subclassOf([signing,an,agreement],[committing]).
subclassOf([star],[astronomical,body]).
subclassOf([solar,system],[collection]).
subclassOf([satellite],[astronomical,body]).
subclassOf([natural,satellite],[satellite]).
subclassOf([natural,satellite],[astronomical,body]).
subclassOf([moon],[natural,satellite]).
subclassOf([planet],[natural,satellite]).
subclassOf([meteorite],[meteoroid]).
subclassOf([meteoroid],[astronomical,body]).
subclassOf([hemisphere],[geographic,area]).
subclassOf([antarctic,area],[land,area]).
subclassOf([land,form],[geographic,area]).
subclassOf([upland,area],[land,form]).
subclassOf([lowland,area],[land,form]).
subclassOf([underground,area],[geographic,area]).
subclassOf([mountain,range],[land,form]).
subclassOf([mountain,range],[upland,area]).
subclassOf([mountain],[land,form]).
subclassOf([mountain],[upland,area]).
subclassOf([hill],[land,form]).
subclassOf([hill],[upland,area]).
subclassOf([volcano],[land,form]).
subclassOf([volcano,status],[internal,attribute]).
subclassOf([volcanic,mountain],[mountain]).
subclassOf([volcanic,mountain],[volcano]).
subclassOf([volcanic,cone],[hill]).
subclassOf([volcanic,cone],[volcano]).
subclassOf([watershed,divide],[land,area]).
subclassOf([watershed,divide],[upland,area]).
subclassOf([sloped,area],[land,form]).
subclassOf([cliff],[sloped,area]).
subclassOf([plateau],[land,form]).
subclassOf([plateau],[upland,area]).
subclassOf([mesa],[land,form]).
subclassOf([mesa],[upland,area]).
subclassOf([butte],[upland,area]).
subclassOf([butte],[land,form]).
subclassOf([piedmont],[land,area]).
subclassOf([plain],[lowland,area]).
subclassOf([valley],[land,form]).
subclassOf([valley],[lowland,area]).
subclassOf([basin],[land,form]).
subclassOf([canyon],[land,form]).
subclassOf([soil,solution],[solution]).
subclassOf([loam],[soil]).
subclassOf([sand],[soil]).
subclassOf([silt],[soil]).
subclassOf([gravel],[rock]).
subclassOf([marble],[rock]).
subclassOf([stone],[rock]).
subclassOf([salt],[compound,substance]).
subclassOf([body,of,water],[water,area]).
subclassOf([body,of,water],[self,connected,object]).
subclassOf([ocean],[salt,water,area]).
subclassOf([ocean],[body,of,water]).
subclassOf([iceberg],[water]).
subclassOf([sea],[salt,water,area]).
subclassOf([sea],[body,of,water]).
subclassOf([water,current],[flow,region]).
subclassOf([water,current],[water,area]).
subclassOf([tide],[flow,region]).
subclassOf([tide],[salt,water,area]).
subclassOf([tidal,process],[internal,change]).
subclassOf([low,tide],[tidal,process]).
subclassOf([lower,low,tide],[low,tide]).
subclassOf([high,tide],[tidal,process]).
subclassOf([higher,high,tide],[high,tide]).
subclassOf([mixed,tide,process],[tidal,process]).
subclassOf([littoral,current],[water,current]).
subclassOf([tidal,flow],[littoral,current]).
subclassOf([tidal,ebb],[littoral,current]).
subclassOf([tidal,bore],[littoral,current]).
subclassOf([rip,current],[littoral,current]).
subclassOf([landlocked,water],[body,of,water]).
subclassOf([salt,lake],[salt,water,area]).
subclassOf([salt,lake],[landlocked,water]).
subclassOf([gulf],[body,of,water]).
subclassOf([gulf],[salt,water,area]).
subclassOf([estuary],[body,of,water]).
subclassOf([estuary],[salt,water,area]).
subclassOf([estuary],[inlet]).
subclassOf([inlet],[body,of,water]).
subclassOf([inlet,passage],[inlet]).
subclassOf([bay],[inlet]).
subclassOf([cove],[inlet]).
subclassOf([sound],[body,of,water]).
subclassOf([strait],[body,of,water]).
subclassOf([channel],[body,of,water]).
subclassOf([inland,water,system],[water,area]).
subclassOf([inland,water,system],[collection]).
subclassOf([lake,region],[geographic,area]).
subclassOf([river],[stream,water,area]).
subclassOf([river],[fresh,water,area]).
subclassOf([river],[body,of,water]).
subclassOf([stream,water,confluence],[water,area]).
subclassOf([river,system],[water,area]).
subclassOf([river,system],[collection]).
subclassOf([waterfall],[stream,water,area]).
subclassOf([canal],[waterway]).
subclassOf([canal],[stationary,artifact]).
subclassOf([canal,structure],[stationary,artifact]).
subclassOf([dam],[stationary,artifact]).
subclassOf([reservoir],[fresh,water,area]).
subclassOf([reservoir],[artifact]).
subclassOf([reservoir,lake],[lake]).
subclassOf([reservoir,lake],[reservoir]).
subclassOf([rapids],[stream,water,area]).
subclassOf([river,mouth],[water,area]).
subclassOf([river,mouth],[stream,water,area]).
subclassOf([creek],[body,of,water]).
subclassOf([creek],[stream,water,area]).
subclassOf([creek],[fresh,water,area]).
subclassOf([irrigation,channel],[artifact]).
subclassOf([irrigating],[motion]).
subclassOf([lake],[static,water,area]).
subclassOf([coastal,plain],[plain]).
subclassOf([river,bank],[shore,area]).
subclassOf([river,bank],[land,form]).
subclassOf([littoral,zone],[geographic,area]).
subclassOf([delta],[land,form]).
subclassOf([peninsula],[land,form]).
subclassOf([cape],[land,form]).
subclassOf([isthmus],[land,area]).
subclassOf([archipelago],[land,form]).
subclassOf([archipelago],[collection]).
subclassOf([archipelagic,area],[geographic,area]).
subclassOf([reef],[land,form]).
subclassOf([coral],[invertebrate]).
subclassOf([coral,reef],[reef]).
subclassOf([atoll],[coral,reef]).
subclassOf([glacier],[land,form]).
subclassOf([cave],[hole]).
subclassOf([cave],[geographic,area]).
subclassOf([burrow],[cave]).
subclassOf([cave,matrix],[land,form]).
subclassOf([submerged,land,area],[geographic,area]).
subclassOf([continental,shelf],[submerged,land,area]).
subclassOf([continental,margin],[submerged,land,area]).
subclassOf([seabed,area],[submerged,land,area]).
subclassOf([seacoast],[shore,area]).
subclassOf([seacoast],[land,form]).
subclassOf([shoreline],[land,area]).
subclassOf([atmosphere],[region]).
subclassOf([atmosphere],[([extension,fn],[fluid])]).
subclassOf([air,stream],[flow,region]).
subclassOf([air,stream],[air]).
subclassOf([jet,stream],[air,stream]).
subclassOf([wind,flow],[air,stream]).
subclassOf([beaufort,number],[relational,attribute]).
subclassOf([weather,season],[weather,process]).
subclassOf([monsoon],[weather,season]).
subclassOf([hurricane,season],[weather,season]).
subclassOf([el,nino],[weather,season]).
subclassOf([weather,system],[weather,process]).
subclassOf([low,pressure,weather,system],[weather,system]).
subclassOf([cyclonicstorm],[low,pressure,weather,system]).
subclassOf([cyclonicstorm],[windstorm]).
subclassOf([tropical,cyclone],[cyclonicstorm]).
subclassOf([typhoon],[tropical,cyclone]).
subclassOf([high,pressure,weather,system],[weather,system]).
subclassOf([storm,system],[weather,system]).
subclassOf([weather,front],[weather,process]).
subclassOf([warm,front],[weather,front]).
subclassOf([cold,front],[weather,front]).
subclassOf([occluded,front],[weather,front]).
subclassOf([stationary,front],[weather,front]).
subclassOf([thunderstorm],[weather,process]).
subclassOf([waterspout],[weather,process]).
subclassOf([hurricane],[weather,process]).
subclassOf([clear,weather],[weather,process]).
subclassOf([partly,cloudy,weather],[weather,process]).
subclassOf([overcast,weather],[weather,process]).
subclassOf([raining],[precipitation]).
subclassOf([freezing,rain],[precipitation]).
subclassOf([snowing],[precipitation]).
subclassOf([sleeting],[precipitation]).
subclassOf([hailing],[precipitation]).
subclassOf([shrub],[flowering,plant]).
subclassOf([lichen],[non,flowering,plant]).
subclassOf([biome],[ecosystem]).
subclassOf([forest],[land,area]).
subclassOf([rain,forest],[biome]).
subclassOf([rain,forest],[forest]).
subclassOf([tropical,rain,forest],[rain,forest]).
subclassOf([temperate,rain,forest],[temperate,hardwood,forest]).
subclassOf([temperate,rain,forest],[rain,forest]).
subclassOf([temperate,hardwood,forest],[biome]).
subclassOf([temperate,hardwood,forest],[forest]).
subclassOf([boreal,forest],[biome]).
subclassOf([boreal,forest],[forest]).
subclassOf([pine,tree],[botanical,tree]).
subclassOf([jungle],[biome]).
subclassOf([jungle],[land,area]).
subclassOf([swamp],[biome]).
subclassOf([desert],[land,area]).
subclassOf([oasis],[biome]).
subclassOf([oasis],[land,area]).
subclassOf([grassland],[biome]).
subclassOf([grassland],[land,area]).
subclassOf([prairie],[grassland]).
subclassOf([prairie],[plain]).
subclassOf([pampa],[grassland]).
subclassOf([pampa],[plain]).
subclassOf([savanna],[grassland]).
subclassOf([savanna],[plain]).
subclassOf([steppe],[plain]).
subclassOf([veldt],[grassland]).
subclassOf([veldt],[plain]).
subclassOf([tundra],[biome]).
subclassOf([tundra],[plain]).
subclassOf([landslide],[geological,process]).
subclassOf([mudslide],[landslide]).
subclassOf([mudflow],[landslide]).
subclassOf([rockslide],[landslide]).
subclassOf([wind,process],[weather,process]).
subclassOf([windstorm],[wind,process]).
subclassOf([strong,wind],[wind,process]).
subclassOf([sirocco],[wind,process]).
subclassOf([harmattan,wind],[wind,process]).
subclassOf([khamsin],[windstorm]).
subclassOf([mistral],[wind,process]).
subclassOf([ghibli],[wind,process]).
subclassOf([chinook,wind],[wind,process]).
subclassOf([pampero],[windstorm]).
subclassOf([squall],[weather,process]).
subclassOf([severe,thunderstorm],[weather,process]).
subclassOf([heavy,raining],[raining]).
subclassOf([dust,storm],[weather,process]).
subclassOf([sandstorm],[weather,process]).
subclassOf([blizzard],[weather,process]).
subclassOf([zud],[weather,process]).
subclassOf([heavy,surf],[weather,process]).
subclassOf([heavy,surf],[water,motion]).
subclassOf([coastal,flooding],[flooding]).
subclassOf([flash,flooding],[flooding]).
subclassOf([maritime,hazard],[land,form]).
subclassOf([reef],[maritime,hazard]).
subclassOf([shoal],[maritime,hazard]).
subclassOf([iceberg],[self,connected,object]).
subclassOf([sea,ice],[ice]).
subclassOf([icing],[weather,process]).
subclassOf([icing],[freezing]).
subclassOf([fogging],[weather,process]).
subclassOf([atmospheric,hazing],[weather,process]).
subclassOf([volcanic,gas,release],[volcanic,eruption]).
subclassOf([land,subsidence],[geological,process]).
subclassOf([locust],[animal]).
subclassOf([swarming],[motion]).
subclassOf([famine],[social,interaction]).
subclassOf([environmental,issue],[area,of,concern]).
subclassOf([soil,quality,issue],[environmental,issue]).
subclassOf([environmental,water,issue],[environmental,issue]).
subclassOf([pollution,issue],[environmental,issue]).
subclassOf([biodiversity,issue],[environmental,issue]).
subclassOf([disease,conditions,issue],[environmental,issue]).
overlapsspatially([middle,east,region],[asia]).
overlapsspatially([caribbean,region],[south,america]).
overlapsspatially([caribbean,region],[north,america]).
overlapsspatially([middle,america],[north,america]).
overlapsspatially([middle,america],[south,america]).
overlapsspatially([central,africa],[northern,hemisphere]).
overlapsspatially([central,africa],[southern,hemisphere]).
overlapsspatially([eastern,africa],[northern,hemisphere]).
overlapsspatially([eastern,africa],[southern,hemisphere]).
overlapsspatially([northern,africa],[eastern,hemisphere]).
overlapsspatially([northern,africa],[western,hemisphere]).
overlapsspatially([western,africa],[eastern,hemisphere]).
overlapsspatially([western,africa],[western,hemisphere]).
overlapsspatially([western,africa],[northern,hemisphere]).
overlapsspatially([western,africa],[southern,hemisphere]).
overlapsspatially([western,europe],[eastern,hemisphere]).
overlapsspatially([western,europe],[western,hemisphere]).
overlapsspatially([southwestern,europe],[eastern,hemisphere]).
overlapsspatially([southwestern,europe],[western,hemisphere]).
overlapsspatially([eastern,south,america],[northern,hemisphere]).
overlapsspatially([eastern,south,america],[southern,hemisphere]).
overlapsspatially([northern,south,america],[northern,hemisphere]).
overlapsspatially([northern,south,america],[southern,hemisphere]).
overlapsspatially([western,south,america],[northern,hemisphere]).
overlapsspatially([western,south,america],[southern,hemisphere]).
overlapsspatially([southern,asia],[northern,hemisphere]).
overlapsspatially([southern,asia],[southern,hemisphere]).
overlapsspatially([southeastern,asia],[northern,hemisphere]).
overlapsspatially([southeastern,asia],[southern,hemisphere]).
overlapsspatially([africa],[northern,hemisphere]).
overlapsspatially([africa],[southern,hemisphere]).
overlapsspatially([south,america],[northern,hemisphere]).
overlapsspatially([south,america],[southern,hemisphere]).
overlapsspatially([antarctica],[eastern,hemisphere]).
overlapsspatially([antarctica],[western,hemisphere]).
overlapsspatially([europe],[eastern,hemisphere]).
overlapsspatially([europe],[western,hemisphere]).
overlapsspatially([asia],[northern,hemisphere]).
overlapsspatially([asia],[southern,hemisphere]).
overlapsspatially([oceania],[northern,hemisphere]).
overlapsspatially([oceania],[southern,hemisphere]).
overlapsspatially([oceania],[eastern,hemisphere]).
overlapsspatially([oceania],[western,hemisphere]).
overlapsspatially([arctic,region],[eastern,hemisphere]).
overlapsspatially([arctic,region],[western,hemisphere]).
overlapsspatially([arctic,ocean],[arctic,region]).
overlapsspatially([tropics],[northern,hemisphere]).
overlapsspatially([tropics],[southern,hemisphere]).
overlapsspatially([tropics],[eastern,hemisphere]).
overlapsspatially([tropics],[western,hemisphere]).
%instanceOf([immediate,instance],[asymmetric,relation]).
instanceOf([immediate,instance],[intransitive,relation]).
instanceOf([central,africa],[geographic,area]).
instanceOf([eastern,africa],[geographic,area]).
instanceOf([northern,africa],[geographic,area]).
instanceOf([southern,africa],[geographic,area]).
instanceOf([western,africa],[geographic,area]).
instanceOf([middle,east,region],[geographic,area]).
instanceOf([central,europe],[geographic,area]).
instanceOf([eastern,europe],[geographic,area]).
instanceOf([northern,europe],[geographic,area]).
instanceOf([southern,europe],[geographic,area]).
instanceOf([western,europe],[geographic,area]).
instanceOf([southeastern,europe],[geographic,area]).
instanceOf([southwestern,europe],[geographic,area]).
instanceOf([north,america],[geographic,area]).
instanceOf([northern,north,america],[geographic,area]).
instanceOf([caribbean,region],[geographic,area]).
instanceOf([middle,america],[geographic,area]).
instanceOf([central,south,america],[geographic,area]).
instanceOf([eastern,south,america],[geographic,area]).
instanceOf([northern,south,america],[geographic,area]).
instanceOf([southern,south,america],[geographic,area]).
instanceOf([western,south,america],[geographic,area]).
instanceOf([central,asia],[geographic,area]).
instanceOf([eastern,asia],[geographic,area]).
instanceOf([northern,asia],[geographic,area]).
instanceOf([southern,asia],[geographic,area]).
instanceOf([southeastern,asia],[geographic,area]).
instanceOf([southwestern,asia],[geographic,area]).
instanceOf([oceania],[geographic,area]).
instanceOf([middle,east,region],[geopolitical,area]).
geographicsubregion([central,africa],[africa]).
geographicsubregion([eastern,africa],[africa]).
geographicsubregion([northern,africa],[africa]).
geographicsubregion([southern,africa],[africa]).
geographicsubregion([western,africa],[africa]).
geographicsubregion([central,europe],[europe]).
geographicsubregion([eastern,europe],[europe]).
geographicsubregion([northern,europe],[europe]).
geographicsubregion([southern,europe],[europe]).
geographicsubregion([western,europe],[europe]).
geographicsubregion([southeastern,europe],[europe]).
geographicsubregion([southwestern,europe],[europe]).
geographicsubregion([northern,north,america],[north,america]).
geographicsubregion([central,south,america],[south,america]).
geographicsubregion([eastern,south,america],[south,america]).
geographicsubregion([northern,south,america],[south,america]).
geographicsubregion([southern,south,america],[south,america]).
geographicsubregion([western,south,america],[south,america]).
geographicsubregion([central,asia],[asia]).
geographicsubregion([eastern,asia],[asia]).
geographicsubregion([northern,asia],[asia]).
geographicsubregion([northern,asia],[northern,hemisphere]).
geographicsubregion([southern,asia],[asia]).
geographicsubregion([southeastern,asia],[asia]).
geographicsubregion([southwestern,asia],[asia]).
geographicsubregion([central,africa],[eastern,hemisphere]).
geographicsubregion([eastern,africa],[eastern,hemisphere]).
geographicsubregion([northern,africa],[northern,hemisphere]).
geographicsubregion([southern,africa],[eastern,hemisphere]).
geographicsubregion([southern,africa],[southern,hemisphere]).
geographicsubregion([middle,east,region],[eastern,hemisphere]).
geographicsubregion([middle,east,region],[western,hemisphere]).
geographicsubregion([eastern,europe],[eastern,hemisphere]).
geographicsubregion([eastern,europe],[northern,hemisphere]).
geographicsubregion([central,europe],[eastern,hemisphere]).
geographicsubregion([central,europe],[northern,hemisphere]).
geographicsubregion([northern,europe],[eastern,hemisphere]).
geographicsubregion([northern,europe],[northern,hemisphere]).
geographicsubregion([southern,europe],[eastern,hemisphere]).
geographicsubregion([southern,europe],[northern,hemisphere]).
geographicsubregion([western,europe],[northern,hemisphere]).
geographicsubregion([southeastern,europe],[eastern,hemisphere]).
geographicsubregion([southeastern,europe],[northern,hemisphere]).
geographicsubregion([southwestern,europe],[northern,hemisphere]).
geographicsubregion([caribbean,region],[northern,hemisphere]).
geographicsubregion([caribbean,region],[western,hemisphere]).
geographicsubregion([middle,america],[northern,hemisphere]).
geographicsubregion([middle,america],[western,hemisphere]).
geographicsubregion([central,south,america],[western,hemisphere]).
geographicsubregion([central,south,america],[southern,hemisphere]).
geographicsubregion([eastern,south,america],[western,hemisphere]).
geographicsubregion([northern,south,america],[western,hemisphere]).
geographicsubregion([southern,south,america],[western,hemisphere]).
geographicsubregion([southern,south,america],[southern,hemisphere]).
geographicsubregion([western,south,america],[western,hemisphere]).
geographicsubregion([central,asia],[eastern,hemisphere]).
geographicsubregion([central,asia],[northern,hemisphere]).
geographicsubregion([eastern,asia],[eastern,hemisphere]).
geographicsubregion([eastern,asia],[northern,hemisphere]).
geographicsubregion([northern,asia],[eastern,hemisphere]).
geographicsubregion([southern,asia],[eastern,hemisphere]).
geographicsubregion([southeastern,asia],[eastern,hemisphere]).
geographicsubregion([southwestern,asia],[eastern,hemisphere]).
geographicsubregion([southwestern,asia],[northern,hemisphere]).
